DEFINE
	COLUMN '__SQDS0VisualCalcs'[Rank] = 
		(/* USER DAX BEGIN */
RANK(DENSE, ROWS, ORDERBY([Sales Value], DESC))
/* USER DAX END */)

	COLUMN '__SQDS0VisualCalcs'[Rank Sales Value] = 
		(/* USER DAX BEGIN */
IF([Rank] <= [Range Value], [Sales Value], [Sales Value])
/* USER DAX END */)

	VAR __SQDS0FilterTable = 
		FILTER(KEEPFILTERS(VALUES('Range'[Range])), 'Range'[Range] = 2)

	VAR __SQDS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL('Product'[Top Group], "IsSQDS0GrandTotalRowTotal", 'Product'[Brand], "IsDM0Total"),
			__SQDS0FilterTable,
			"Sales_Value", 'Sales'[Sales Value],
			"Range_Value", IGNORE('Range'[Range Value])
		)

	VAR __SQDS0VisualCalcsInput = 
		SELECTCOLUMNS(
			KEEPFILTERS(
				SELECTCOLUMNS(
					__SQDS0Core,
					"Top_Group", 'Product'[Top Group],
					"IsSQDS0GrandTotalRowTotal", [IsSQDS0GrandTotalRowTotal],
					"Brand", 'Product'[Brand],
					"IsDM0Total", [IsDM0Total],
					"Sales_Value", [Sales_Value],
					"Range_Value", [Range_Value]
				)
			),
			"Top Group", [Top_Group],
			"Brand", [Brand],
			"IsSQDS0GrandTotalRowTotal", [IsSQDS0GrandTotalRowTotal],
			"IsDM0Total", [IsDM0Total],
			"Sales Value", [Sales_Value],
			"Range Value", [Range_Value]
		)

	TABLE '__SQDS0VisualCalcs' = 
		__SQDS0VisualCalcsInput
		WITH VISUAL SHAPE
			AXIS rows
				GROUP [Top Group] TOTAL [IsSQDS0GrandTotalRowTotal]
				GROUP [Brand] TOTAL [IsDM0Total]
				ORDER BY
					[Top Group] DESC,
					[Brand] ASC
			DENSIFY "IsDensifiedRow"

	VAR __SQDS0RemoveEmptyDensified = 
		FILTER(
			KEEPFILTERS('__SQDS0VisualCalcs'),
			OR(
				OR(
					NOT('__SQDS0VisualCalcs'[IsDensifiedRow]),
					NOT(ISBLANK('__SQDS0VisualCalcs'[Rank]))
				),
				NOT(ISBLANK('__SQDS0VisualCalcs'[Rank Sales Value]))
			)
		)

	VAR __DS0Core = 
		SELECTCOLUMNS(
			KEEPFILTERS(
				FILTER(
					KEEPFILTERS(__SQDS0RemoveEmptyDensified),
					AND(
						'__SQDS0VisualCalcs'[IsSQDS0GrandTotalRowTotal] = FALSE,
						'__SQDS0VisualCalcs'[IsDM0Total] = TRUE
					)
				)
			),
			"'__SQDS0VisualCalcs'[Top Group]", '__SQDS0VisualCalcs'[Top Group],
			"'__SQDS0VisualCalcs'[Sales Value]", '__SQDS0VisualCalcs'[Sales Value],
			"'__SQDS0VisualCalcs'[Rank]", '__SQDS0VisualCalcs'[Rank],
			"'__SQDS0VisualCalcs'[Rank Sales Value]", '__SQDS0VisualCalcs'[Rank Sales Value],
			"'__SQDS0VisualCalcs'[Range Value]", '__SQDS0VisualCalcs'[Range Value]
		)

	VAR __DS0RemoveContextOnlyColumns = 
		SELECTCOLUMNS(
			KEEPFILTERS(__DS0Core),
			"'__SQDS0VisualCalcs'[Top Group]", '__SQDS0VisualCalcs'[Top Group],
			"'__SQDS0VisualCalcs'[Rank Sales Value]", '__SQDS0VisualCalcs'[Rank Sales Value],
			"'__SQDS0VisualCalcs'[Range Value]", '__SQDS0VisualCalcs'[Range Value]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(1001, __DS0RemoveContextOnlyColumns, '__SQDS0VisualCalcs'[Top Group], 0)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	'__SQDS0VisualCalcs'[Top Group] DESC