table Propotional
	lineageTag: 61c79b95-a45f-434a-8415-440f0071ddf5

	measure 'Size I' = SUM(Propotional[Value])
		lineageTag: c61d7550-48c0-4446-91a3-c3077102a683

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Category
		dataType: string
		lineageTag: 902504dc-f682-41d4-968b-3ddac1402444
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Attribute
		dataType: string
		lineageTag: 95667170-b047-496f-8729-7273eeb70595
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: int64
		formatString: 0
		lineageTag: a3a43adf-ab55-4598-b225-75a861c1b7bf
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

	partition Propotional = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WclTSUTI0ARJmSrE60UpOIK4ZiDAC850hTB0lIwMw3wXEN0fIu8LkgYIgvhuQaWwAJEyB6mMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Category = _t, #"Our Share" = _t, #"Main competitor" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Our Share", Int64.Type}, {"Main competitor", Int64.Type}}),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Changed Type", {"Category"}, "Attribute", "Value")
				in
				    #"Unpivoted Other Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

