table Split
	lineageTag: 6959a099-9a1b-4b92-bcb5-7e225bc3feb1

	measure 'Checked Image' = ```
			
			"data:image/svg+xml;utf8," &
			"<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' viewBox='0 0 100 100'>
			  <rect width='100' height='100' fill='white' stroke='black' stroke-width='5'/>
			  <polyline points='20,50 40,70 80,30' fill='none' stroke='black' stroke-width='8'/>
			</svg>"
			
			```
		lineageTag: ac9efdb6-362f-426d-887e-72346a28a3b6
		dataCategory: ImageUrl

	column Split
		dataType: string
		lineageTag: 828ce61f-c868-4993-9a31-8679c675be73
		summarizeBy: none
		isDataTypeInferred
		sourceColumn: [Value1]
		sortByColumn: 'Split Order'

		relatedColumnDetails
			groupByColumn: 'Split Fields'

		annotation SummarizationSetBy = Automatic

	column 'Split Fields'
		dataType: string
		isHidden
		lineageTag: a2508819-c9f3-48c4-9920-8c16bbec698c
		summarizeBy: none
		isDataTypeInferred
		sourceColumn: [Value2]
		sortByColumn: 'Split Order'

		extendedProperty ParameterMetadata =
				{
				  "version": 3,
				  "kind": 2
				}

		annotation SummarizationSetBy = Automatic

	column 'Split Order'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 99f94041-22cc-4523-b1f7-0f39b7d6fc55
		summarizeBy: sum
		isDataTypeInferred
		sourceColumn: [Value3]

		annotation SummarizationSetBy = Automatic

	partition Split = calculated
		mode: import
		source =
				{
				    ( "Category", NAMEOF('Product'[Category]), 0),
				    ("Brand", NAMEOF('Product'[Brand]), 2),
				    ("Manufacturer", NAMEOF('Product'[Manufacturer]), 3)
				}

	annotation PBI_Id = 7432f966801b47a096cbe11788009dc9

